### PR TITLE
Adds alt implementation

### PR DESCRIPTION
**Pull request by goatslacker**
Hi there!

Your project is a great "todomvc" of flux implementations, this is a neat idea and I can't wait to read your blog post.

This PR adds the [alt](https://github.com/goatslacker/alt) implementation for comparison. Alt is a terse flux implementation, similar to reflux I guess, but it's actually 100% flux. It's got tests, docs, and it's being used in production right now.

Alt is meant to be used with ES6 although it's not necessary. I can actually provide a non ES6 example. In this PR I'm using [6to5](http://6to5.org) to transpile the code with browserify.

I tested this PR by
- cloning a fresh repo
- run `npm install`
- run `npm start`
- `open index.html`
- clicked on 2 iPads and verified they sold out.
- clicked on 1 shirt
- checkout
- verified console that correct items were logged

### CODE REVIEW

**Comment by voronianski** [comment]
@goatslacker thanks for your solution! :star:  it looks solid and really has more of reflux feel. It definitely deserves to be promoted better, keep rocking! :wink:

**Comment by goatslacker** [comment]
Cheers, you keep rocking as well.

**Comment by leszekhanusz** [comment]
Hi,

I wanted to try a more complete implementation of isomorphic flux with alt to see how it would work with a real API between the server and the client (using socket.io).

So I added a cartCheckout API call to validate the checkout on server and update the inventory of the future clients.

You can check the fork here:
https://github.com/leszekhanusz/flux-comparison

Should I make a pull request ?

**Comment by goatslacker** [comment]
I like the idea of having a more complex candidate for the isomorphic flux examples.

**Comment by leszekhanusz** [comment]
@goatslacker Thanks a lot for reviewing my code.

I added some answers to your comments in the commit, tdlr:
- I don't want to flush because the store is share between all the users
- I need the assign when getting a product from the store because it is possible to mutate an element of the store from the view

**Pull request merged**
